# Generated by Django 4.1.1 on 2022-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellPhone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('restaurantName', models.CharField(max_length=50)),
                ('social', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=256)),
                ('address', models.TextField(max_length=256)),
            ],
        ),
    ]
