# Generated by Django 4.1.1 on 2022-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_userrestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurant',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
